name: PR Test Building Package for CentOS Stream 8

on:
  push:
    paths:
    - 'build/centos-stream-8/**'

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Build libvirt
        uses: ./build/centos-stream-8/pkg-builder
        with:
          package: intel-mvp-tdx-libvirt
      - name: Cleanup
        run: |
          rm -rf *
      - name: Build tdx-guest-kernel
        uses: ./build/centos-stream-8/pkg-builder
        with:
          package: intel-mvp-tdx-guest-kernel
      - name: check dir
        run: |
          ls -lah
